version: '3'
services:
  app:
    image: local/whisper:1.0
    volumes:
      - ./app/:/app:delegated
      - ./models/medium.pt:/root/.cache/whisper/medium.pt
    ports:
      - '80:80'
    entrypoint: flask --app main run --host=0.0.0.0 --port=80
